enable-module-update = false # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
arch = "arm64-v8a"
cli-version = "dev"
patches-version = "dev"
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit-Morphe]
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Twitter-Morphe]
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
include-stock = "split"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Adguard-Morphe]
app-name = "Adguard"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"

[Automate-Morphe]
app-name = "Automate"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/llamalab/automate-llamalab/"
uptodown-dlurl = "https://automate-beta.en.uptodown.com/android"

[CamScanner-Morphe]
app-name = "CamScanner"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"

[Duolingo-Morphe]
app-name = "Duolingo"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"

[Eyecon-Morphe]
app-name = "Eyecon"
patches-source = "/Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/eyecon-phone-dialer-contacts/eyecon-caller-id-spam-block/"
uptodown-dlurl = "https://eyecon-phone-dialer-and-cont-eyecon.en.uptodown.com/android"
