enable-module-update = false # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
arch = "arm64-v8a"
build-mode = "apk"
dpi = "nodpi anydpi 120-640dpi"
#cli-version = "dev"
#patches-version = "dev"
# add 'enabled = true' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Google-Photos-Morphe]
rv-brand = "Morphe"
enabled = true
app-name = "Photos"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
included-patches = """\
    'Enable DCIM folders backup control' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Instagram-Morphe]
rv-brand = "Morphe"
enabled = true
include-stock = "split"
app-name = "Instagram"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Music-Morphe]
rv-brand = "Morphe"
enabled = true
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Proton-Vpn-Hoodles-Morphe]
rv-brand = "Morphe-Hoodles"
enabled = true
app-name = "Proton VPN"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Proton-Vpn-Paresh-Morphe]
rv-brand = "Morphe-Paresh"
app-name = "Proton VPN"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-gitlab = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Reddit-Morphe]
rv-brand = "Morphe"
enabled = true
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Splitwise-Morphe]
rv-brand = "Morphe"
enabled = true
app-name = "Splitwise"
patches-source = "abhis1n/Morphe-Patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise"
uptodown-dlurl = "https://splitwise.en.uptodown.com/android"

[YouTube-Morphe]
rv-brand = "Morphe"
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
